PAX: Fix guc name to not contain dot
The GUC name should not contain dot `.`, because setting non-exist
guc name doesn't raise an error. It's confusing if the user spells
the wrong guc name.

```
gpadmin=# set pax.abcdefg = on;
SET
gpadmin=# set pax_abcdefg = on;
ERROR:  unrecognized configuration parameter "pax_abcdefg"
```