Bugfix : Make Pax file directory structure consisitency for set new tablespace case.
Problem: The PAX file path directory structure is not consistency for set new tablesapce cases. Currently if the source file directory is emptry then it will skip to copy data as well as the destination directory creation. The problem will be raised when the next time set new table space DDL executed, if the source directory is empty, the assert in ListDirectory will be raised and caused exception.

Fix: The fix should be creating the destination pax directoy even if source directory is empty, which makes the source/destination directory structure consistency in set new tablesapce DDL execution.

```
std::vector<std::string> LocalFileSystem::ListDirectory(
    const std::string &path) const {
  ...

  Assert(filepath != NULL && filepath[0] != '\0');

  dir = opendir(filepath);
  CBDB_CHECK(dir, cbdb::CException::ExType::kExTypeFileOperationError);

  ...
}

```

```
,sx1,"ERROR","XX000","ERROR: RelationCopyData (pax_access_handle.cc:194)",,,,,,"ALTER TABLE ALL IN TABLESPACE regress_tblspace_renamed SET TABLESPACE pg_default;",0,,"pax_access_handle.cc",194,"Stack trace:
1    0x7f6aa6f1f8e8 libpostgres.so errstart + 0x208
2    0x7f6a998f2fc5 pax.so _ZN3pax17CCPaxAccessMethod16RelationCopyDataEP12RelationDataPK11RelFileNode + 0x9d
3    0x7f6aa6b2c889 libpostgres.so <symbol not found> + 0xa6b2c889
4    0x7f6aa6b3d3ca libpostgres.so <symbol not found> + 0xa6b3d3ca
5    0x7f6aa6b3e76f libpostgres.so AlterTableMoveAll + 0x2bf
6    0x7f6aa6dbfb39 libpostgres.so <symbol not found> + 0xa6dbfb39
7    0x7f6aa6dbe4e9 libpostgres.so standard_ProcessUtility + 0x169
8    0x7f6aa6dbcb13 libpostgres.so <symbol not found> + 0xa6dbcb13
9    0x7f6aa6dbcc64 libpostgres.so <symbol not found> + 0xa6dbcc64
10   0x7f6aa6dbd3cb libpostgres.so PortalRun + 0x2bb
11   0x7f6aa6db75c4 libpostgres.so <symbol not found> + 0xa6db75c4
12   0x7f6aa6dbac9a libpostgres.so PostgresMain + 0x1fda
13   0x7f6aa6d031d3 libpostgres.so <symbol not found> + 0xa6d031d3
14   0x7f6aa6d04305 libpostgres.so PostmasterMain + 0xe45
15   0x4017c0 postgres main (main.c:198)
16   0x7f6aa5fdb555 libc.so.6 __libc_start_main + 0xf5
17   0x4019c4 postgres <symbol not found> + 0x4019c4
```

Test:

```
postgres=# \!rm -rf /tmp/t_pax73
postgres=# \!mkdir /tmp/t_pax73
postgres=# drop tablespace test73;
ERROR:  tablespace "test73" does not exist
postgres=# create tablespace test73 location '/tmp/t_pax73';
CREATE TABLESPACE
postgres=# create table t_pax73(a int, b int) using pax;
NOTICE:  Table doesn't have 'DISTRIBUTED BY' clause -- Using column named 'a' as the Cloudberry Database data distribution key for this table.
HINT:  The 'DISTRIBUTED BY' clause determines the distribution of data. Make sure column(s) chosen are the optimal data distribution key to minimize skew.
CREATE TABLE
postgres=# insert into t_pax73 select i ,i from generate_series(1,1000) i;
INSERT 0 1000
postgres=# alter table t_pax73 set tablespace test73;
ALTER TABLE
postgres=# insert into t_pax73 select i ,i from generate_series(1,1000) i;
INSERT 0 1000
postgres=# select count(1) from t_pax73;
 count
-------
  2000
(1 row)

postgres=# alter table t_pax73 set tablespace pg_default;
ALTER TABLE
postgres=# insert into t_pax73 select i ,i from generate_series(1,1000) i;
INSERT 0 1000
postgres=# alter table t_pax73 set tablespace test73;
ALTER TABLE
postgres=# select count(1) from t_pax73;
 count
-------
  3000
(1 row)
```