Fix: operator may not match opfamily
`ERROR:  operator 1209 is not a member of opfamily 4056 (lsyscache.c:164)`

cause the by `like clauses`.

ex.
```
select * from table where text_type_column like 'Unknown%';
```